name: test_backendless
version: 0.0.1
description: An absolute bare-bones web app.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  crypto: any
  umiuni2d_netbox:
    path: ../../
  flutter:
    path: /Users/kyorohiro/tools/git/flutter_master/packages/flutter

dev_dependencies:
  unittest: any

transformers:
- dart_to_js_script_rewriter
